### ISSUE TITLE
Incompatible with Update 5

### ISSUE THREAD

**Issue by Genda1ph** [Turtlefight/SatisfactoryFluidResourceSink#1]
Hey,

I've installed this mod on the most recent Steam build and Satisfactory crashed on start with an error `Plugin 'FluidResourceSink' failed to load because module 'FluidResourceSink' could not be loaded.`

I believe mod needs to be updated.

**Comment by Turtlefight** [comment]
Hi, sorry last week has been a bit busy for me so i didn't manage to update it for the U5 Release.
I've updated it now for U5, Version 1.1.1 of Fluid AWESOME Sink should work now on EA & EXP :)
